
//! Autogenerated weights for `pallet_letters`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-22, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_letters
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./runtime/src/weights/pallet_letters.rs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for pallet_letters.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_letters::WeightInfo for WeightInfo<T> {
	// Storage: Letters OwnedLetersArray (r:1 w:1)
	fn reimburse() -> Weight {
		(217_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
